### ISSUE TITLE
Functions mentioned don't exist

### ISSUE THREAD

**Issue by fremontmj** [glennsl/bs-json#27]
In the Json.mli file there is a comment (below) that mentions the `reifyType` and `test` functions.  I don't think these functions exist in the repo.
```
Decoding is a more complex process, due to the highly dynamic nature of JSON
data structures. There are several ways to decode a JSON data structure,
depending on your needs. This module provides two fairly low level methods
of decoding, the assertive, more convenient but also more rigid {! Decode}
module and the more flexible but cumbersome {! reifyType} and {! test} functions.
The third way is to use a opinionated third-party APIs that makes other tradeoffs.
```

**Comment by glennsl** [comment]
Thanks. This is a remnant from when it was intended to be included in bs-platform. `reifyType`, which is now called `classify`, and `test` is in the `Js.Json` module that ships with `bs-platform`.
