### ISSUE TITLE
How to decode a large tuple?

### ISSUE THREAD

**Issue by fremontmj** [glennsl/bs-json#28]
The repo provides `tuple2`, `tuple3`, and `tuple4` functions.  I have some incoming JSON that includes stuff like this: `["Q",-223.5,473,-221.5,471.5]`.  I made a tuple5 function, solving my problem, but, generally, if there are incoming tuples that are long and have multiple types within them (so you can't use list or array), how might one decode them?

Thanks much!

**Comment by glennsl** [comment]
You'd have to write your own decoder, like you have. Alternatively, you could decode it as a list or array of some variant if that makes more sense. That would still involve custom decoders, but much simpler ones that just wrap the result of `string` or `int` in a variant so you get a common type.

Large tuples is an anti-pattern that I don't think should be encouraged (even `tuple4` is pushing it), and writing custom decoders should be considered normal, not a hack.
