### ISSUE TITLE
Breaking changes in bs-platform 3.1.0

### ISSUE THREAD

**Issue by ncthbrt** [glennsl/bs-json#37]
Bs-platform has removed `Js.Boolean.to_js_boolean` and `Js.Boolean.t`. Need to revert the earlier revert.

**Comment by glennsl** [comment]
Done. Released as 2.0.0. Thanks for reporting! :)

**Comment by ncthbrt** [comment]
Thanks you for the prompt fix :)

**Comment by Anahkiasen** [comment]
@glennsl Could it be pushed to NPM? Latest there is currently still 1.0.1 https://www.npmjs.com/package/bs-json
