### ISSUE TITLE
int decoder allows range violations

### ISSUE THREAD

**Issue by dvisztempacct** [glennsl/bs-json#42]
In ReasonML:
```
let x = Json.Decode.int([%bs.raw "0x80000000"]);
Js.log2(x, x*1)
```

Result:
```
2147483648 -2147483648
```

**Comment by glennsl** [comment]
`int` is by definition a platform-dependent type, and it isn't the value returned from the `int` decoder that is incorrect and causes issues, but the operation performed on the value that causes issues, in this case multiplication.

While I can see the argument for `bs-json` doing range validation since it does other kinds of validation, I don`t think it should be making assumptions about the behavior of `bs-platform`

**Comment by dvisztempacct** [comment]
In my uses, `bs-json` lives right at the edge between ocaml and javascript. It would be very useful for me if `bs-json` did concern itself with validation. Maybe I just don't know what `bs-json` is supposed to do.

That said, I'll try my best to make a convincing argument. Or maybe ask enough questions that I will understand a little better.

>`int` is by definition a platform-dependent type

Does `bs-json` target other platforms? Lines [like this](https://github.com/glennsl/bs-json/blob/master/src/Json_decode.ml#L3) lead me to believe it does not.

```ocaml
external _stringify : Js.Json.t -> string = "JSON.stringify" [@@bs.val]
```

>it isn't the value returned from the `int` decoder that is incorrect and causes issues, but the operation performed on the value

I don't understand this perspective at all. The `int` type, per platform, represents a specific set of values, and the value physically assigned to the javascript variable representing our ocaml variable is not a member of that set.

Extending your line of reasoning will very quickly lead us to conclude that `bs-json` belongs among other unsafe type aliasing operations such as `external`, `%bs.raw`, and `%identity`, or worse, that the type checker has no practical value.

>While I can see the argument for `bs-json` doing range validation since it does other kinds of validation, I don't think it should be making assumptions about the behavior of `bs-platform`.

It's true that `bs-json` does other kinds of validation. The `int` decode  itself validates its argument!

https://github.com/glennsl/bs-json/blob/master/src/Json_decode.ml#L5-L6
```ocaml
let _isInteger value =
  Js.Float.isFinite value && Js.Math.floor_float value == value
```

[The correct validation code](https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBA+glgzgSQHZhAcxAJwgLggKTgDpCB7JIyAXgD4IAjU04CKiAbQFJ7jMBDAO4QARAA9aAClEAfAAwBKKlVHCAugG4AUJtCRRcXBD6Z+ATwmESccpXmsO3XoJHtNECABYATABoIXgGYiAFYfNwgAWT4wAAsiAAdSAQlfAIBGeQBaNL8o2ISklJ90+TD3TLy4xOTUjL8K6KrC2qy0zVU1LU19CGk6AEETPlMiAFs+eKlWOktgUjQvKT9RXqJoeGRUDEx5eSA) fails for any value outside the domain of bucklescript's `int` type, and I strongly suspect is more performant than the existing validation that `int` provides.

If you don't want `int` to do this, would you consider providing a second decoder which completely validates its argument?

Thanks!
