### ISSUE TITLE
Reopen Issue #42?

### ISSUE THREAD

**Issue by dvisztempacct** [glennsl/bs-json#45]
I couldn't find a button to re-open issue #42 to bring it to your attention :)

Please let me know your thoughts!

**Comment by glennsl** [comment]
Hey. No need to make a new issue, just make a comment on the existing one. Anyway, I'm aware of it, but have a number of other issues needing a response and plenty of other things to do as well. It's a good comment that deserves a good response, but doesn't seem like it's very time-sensitive. I'll get to it eventually :)
