### ISSUE TITLE
The value toJSONUnsafe can't be found in Js.Date

### ISSUE THREAD

**Issue by Tevinthuku** [glennsl/bs-json#46]
Im getting this error

```
  13 │ 
  14 │ let date d =
  15 │   d |> Js.Date.toJSONUnsafe
  16 │     |> string

  The value toJSONUnsafe can't be found in Js.Date    at Array.map (<anonymous>)

```

What could be the problem

**Comment by glennsl** [comment]
You're likely using an outdated version of `bs-platform`. The latest release of `bs-json` requires `bs-platform` >= 4.0.2, and you should have gotten warnings about that from npm unless you forcibly downhraded `bs-platform` after installing `bs-json`.
