### ISSUE TITLE
Handling fields that may not exist

### ISSUE THREAD

**Issue by abradley2** [glennsl/bs-json#47]
If a field is `undefined` it doesn't serialize to a keyed field in Json. It just won't be there.

So in my case if I have a field that may or may not exist at all (not simply be on the object but null)

Here's a short example:
```
let decodeTodos =
  Json.Decode.array(item =>
    Json.Decode.{
      notes: item |> field("notes", optional(string)),
    }
  );

let decoded = decodeTodos(Js.Json.parseExn("[{}]"));
```

This leads to the error `Expected field 'notes'`

Is there a way to deal with these fields?

[link to example showcase](https://codesandbox.io/s/mj8pnm77rp)

My current work around is
```
notes:
        item
        |> Json.Decode.withDefault(None, field("notes", optional(string))),
```

**Comment by glennsl** [comment]
You can just move `optional` outside `field`:

```reason
  notes: item |> optional(field("notes", string)),
```

This will return `None` if either `field` or `string` fails.
