### ISSUE TITLE
Package fails to build

### ISSUE THREAD

**Issue by nickretallack** [glennsl/bs-json#53]
```
  We've found a bug for you!
  /Users/nick/Documents/GitHub/reason-react-newer/node_modules/@glennsl/bs-json/src/Json_encode.ml 15:8-27
  
  13 │ 
  14 │ let date d =
  15 │   d |> Js.Date.toJSONUnsafe
  16 │     |> string
  17 │ 
  
  The value toJSONUnsafe can't be found in Js.Date
```

**Comment by nickretallack** [comment]
Changing `toJSONUnsafe` to `toJSON` seems to have fixed it.

**Comment by glennsl** [comment]
Looks like your bs-platform is outdated. What does `bsb -version` and `npx bsb -version` say? It should be > 4.0.7 I think.

**Comment by nickretallack** [comment]
Ah, it seems like there was some confusion between `npm` and `yarn`.  I've uninstalled `bs-platform` with both and then reinstalled with one and now I have version 4 in my path.

**Comment by glennsl** [comment]
Great, I assume it's solved and that I can close this then?
