### ISSUE TITLE
Encode Integer into an Array of Integer

### ISSUE THREAD

**Issue by mkhuda** [glennsl/bs-json#65]
Hi, I have small problem when using *bs-json*. In some cases, I want to convert an integer into an array of integer e.g `[1]` or `[0]`. But I am still confusing how to do it with `Json.Encode` for sending through request payload.

I have read the examples of 
```
let _ =
  [| "foo"; "bar" |]
  |> Json.Encode.stringArray
  |> Json.stringify
  |> Js.log
```
But it's array of string.

Thank you very much.

**Comment by glennsl** [comment]
Hey. Not entirely sure what you're asking, but sounds like `Json.Encode.(array(int))` should do what you want.
