### ISSUE TITLE
upgrade peerdependency bs-platform

### ISSUE THREAD

**Issue by BlueHotDog** [glennsl/bs-json#67]
any reason why this lib needs bs-platform 5? 7 is out already

**Comment by glennsl** [comment]
Just that noone's bumped it yet. It should work perfectly fine with 7, but you might get a warning.

I can't even remember why the `peerDepdendency` was added, so not sure it has any purpose anymore.

**Comment by banacorn** [comment]
I can't publish my vscode extension because of this :(

```bash
$ vsce package
 ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! peer dep missing: bs-platform@^5.0.4, required by @glennsl/bs-json@5.0.2
```

**Comment by banacorn** [comment]
For those who need a version without the `peerDepdendency`, please consider [this fork](https://github.com/idkjs/bs-json/commit/806779b980320d606a019ad42d77f4a02bbdb0e4) by @idkjs :D

Simply changing the `dependencies` field in you `package.json` to 
```json
   "@glennsl/bs-json": "github:idkjs/bs-json#806779b",
```
would do
