### ISSUE TITLE
Map?

### ISSUE THREAD

**Issue by drewbitt** [glennsl/bs-json#68]
Maybe I'm missing it, but I'm not seeing any map usage to a field in any documentation and would encourage that to be improved. I'm a beginner to Reason / ML.

My json consists of a string url, boolean self, media which is a dict. I don't care what's in media, I just need to know if it's an empty dict (it's fields/types aren't known at runtime anyway). So wanting to decode media as a bool.

My idea:
```reason
let decodeJson = json =>
  Json.Decode.{
    url: json |> field("url", string),
    self: json |> field("self", bool),
    media: json |> field("media", map(x=> x == Js.null)), // maybe Js.Dict.empty?
  };
```
```
 This has type:
    Json.Decode.decoder(Js.null('a)) => Json.Decode.decoder(bool)
  But somewhere wanted:
    Json.Decode.decoder('b) (defined as Js.Json.t => 'b)

  The incompatible parts:
    Json.Decode.decoder(Js.null('a)) (defined as Js.Json.t => Js.null('a))
    vs
    Js.Json.t (defined as Js.Json.t)
```
I'm sure I'm not understanding a lot here.

**Comment by glennsl** [comment]
There are examples in the docstrings:

https://github.com/glennsl/bs-json/blob/913182be2b473a600ff32fb7f43308d6ac88ed6f/src/Json_decode.mli#L428-L440

Sounds like what you want is `dict`, not `map`:

https://github.com/glennsl/bs-json/blob/913182be2b473a600ff32fb7f43308d6ac88ed6f/src/Json_decode.mli#L280-L299

**Comment by glennsl** [comment]
Oh, I see you want `media` to be a bool.  Then either

```reason
media: json |> optionall(field("media", dict(value))) == Some(Js.Dict.empty),
```

or

```reason
media: json |> field("media", dict(value)) == Js.Dict.empty,
```

should work, depending on whether you want the absence of the field to be considered an error or not.

**Comment by drewbitt** [comment]
Thanks! Maybe I was a bit misunderstood. The latter method would require me to still create all the fields for the dict though when doing `dict(value)`. I mentioned that the field names and types aren't known at runtime if it does indeed have data. Is there a way to avoid using the explicit typing of each json field if just looking if any are present? If the solution is to follow the dynamic dict example, OK, but I thought I was missing something more relevant like using map.

**Comment by glennsl** [comment]
Why would it require you to create all the fields?

> Is there a way to avoid using the explicit typing of each json field if just looking if any are present?

Yes, using `value` will ignore the type of the field. It'll just be returned as an opaque `Js.Json.t` value, so the type of the dict would be `Js.Dict.t(Js.Jsont.t))`

> but I thought I was missing something more relevant like using map.

What would you map it to? If you just want to know whether it's empty or not you can just compare against `Js.DIct.empty` directly. An empty dict is just empty, it doesn't have contents of any specific type.

**Comment by drewbitt** [comment]
>Why would it require you to create all the fields?
> Yes, using `value` will ignore the type of the field. It'll just be returned as an opaque `Js.Json.t` value, so the type of the dict would be `Js.Dict.t(Js.Jsont.t))`

I do not have `value`; since I don't have the variable bound, I assumed you wrote it as a placeholder for a type. `The value value can't be found`

```
let decodeRedditPostData = json =>
  Json.Decode.{
    url: json |> field("url", string),
    self: json |> field("is_self", bool),
    media: json |> field("media", dict(value)) == Js.Dict.empty,
  };
```
I appreciate the explanation nevertheless.

**Comment by glennsl** [comment]
Oh, sorry, it's not called `value`, but [`id`](https://github.com/glennsl/bs-json/blob/master/src/Json_decode.mli#L18-L33). It's called `value` in `ocaml-decoders`, which is what I use these days. :flushed:
