### ISSUE TITLE
Convert to rescript

### ISSUE THREAD

**Issue by pbiggar** [glennsl/bs-json#92]
Hi, would there be interest in a PR converting the repo to rescript 9.1? If so, are there any concerns or preferences around it (such as versions to support in the build matrix)?

**Comment by glennsl** [comment]
Just published at https://www.npmjs.com/package/@glennsl/rescript-json-combinators



I haven't actually tested using the published in a project though, so please let me know if there's any problems, or if the instructions are wrong.
